# Use an official Python runtime as a parent image
FROM python:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 80
# Define environment variable
ENV FLET_APP_MODULE=app.py

# Run app.py when the container launches
CMD ["flet", "run", "--host=0.0.0.0", "--port=80"]